---
name: release

on:
  pull_request:
    types: [ready_for_review]

jobs: 
  build_release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
        map_type: 
          - name: small
            size: 1000
          - name: medium
            size: 5000
          - name: large
            size: 10000

    outputs:
          release_tag: ${{ steps.version.outputs.release_tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
          
      - name: Install EBPF Packages
        run: | 
          name: tproxy_splicer_${{matrix.map_type.name}}
          path: ./tproxy_splicer_${{matrix.map_type.name}}.tar.gz
          
      - name: Get version
        id: version
        run: |
          version=`files/objects/map_update -V`
          echo "::set-output name=release_tag::$version"
          
  create_release:
    runs-on: ubuntu-22.04
    needs: build_release 
    steps:
      - name: Download tproxy tar files from build_release
        uses: actions/download-artifact@v3

      - name: Create release
        uses: actions/create-release@v1
        id: release
        with:
          draft: false
          prerelease: false
          release_name: v${{ needs.build_release.outputs.release_tag }}
          tag_name: v${{ needs.build_release.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload a small artifact for release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: tproxy_splicer_small/tproxy_splicer_small.tar.gz
          asset_name: tproxy_splicer_small
          asset_content_type: application/gzip
          
      - name: Upload a medium artifact for release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: tproxy_splicer_medium/tproxy_splicer_medium.tar.gz
          asset_name: tproxy_splicer_medium
          asset_content_type: application/gzip
          
      - name: Upload a large artifact for release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: tproxy_splicer_large/tproxy_splicer_large.tar.gz
          asset_name: tproxy_splicer_large
          asset_content_type: application/gzip
